name: Sync to GitLab

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "${{ secrets.GIT_USER }}"
        git config --global user.email "rastgooasma835@gmail.com"  # Change to your email

    - name: Mirror to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
      run: |
        # Add GitLab remote
        git remote add gitlab $GITLAB_REPO
        # Push to GitLab
        git push --mirror gitlab
