name: Sync to GitLab

on:
  push:
    branches:
      - newmain  # Change to your default branch if different

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "${{ secrets.GITLAB_USERNAME }}"
        git config --global user.email "${{ secrets.GITLAB_EMAIL}}"  # Change to your email

    - name: Mirror to GitLab
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
      run: |
        # Add GitLab remote
        git remote add gitlab "https://${GITLAB_TOKEN}@${GITLAB_REPO#https://}"
        # Push to GitLab
        git push --mirror gitlab
